
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../../components/Navbar/Navbar";
import Footer from "../../components/Footer/footer";
import { Provider } from "react-redux";

import ReduxProvider from "./reduxProvider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>

  );
}
